name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  PMD-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
      uses: action//checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
